# Limitar la memoria para que Windows no se congele (1.5GB es el punto dulce para 4GB totales)
org.gradle.jvmargs=-Xmx1536M -XX:MaxMetaspaceSize=256m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8

# El Daemon ayuda a que las siguientes compilaciones sean un poco más rápidas
org.gradle.daemon=true

# IMPORTANTE: Desactivamos el procesamiento paralelo para no saturar tu procesador de 12 años
org.gradle.parallel=false

# Las líneas que ya tenías y que son obligatorias
android.useAndroidX=true
android.enableJetifier=true
org.gradle.java.home=C:/Program Files/Java/jdk-17